import math
from typing import Optional, List
from .base import BasePostProcessor

class GrblPostProcessor(BasePostProcessor):
    """
    Grbl CNC Controller Dialect (e.g. Inventables X-Carve with Arduino/gShield).
    - Strict linear expansion (No canned cycles like G81/G83)
    - Dwell specified in seconds: G4 P<seconds>
    - Feed rate in mm/min (or in/min) under G94 mode
    """

    dialect_name: str = "grbl"
    supports_canned_cycles: bool = False

    def format_header(
        self,
        units: str = "mm",
        absolute_mode: bool = True,
        feed_mode: str = "G94",
        plane: str = "G17",
        comment: Optional[str] = None,
    ) -> List[str]:
        unit_code = "G21" if units.lower() in ("mm", "metric") else "G20"
        dist_code = "G90" if absolute_mode else "G91"
        header = [
            "(Generated by Conversational CNC Controller)",
            f"{unit_code} {dist_code} {feed_mode} {plane}",
        ]
        if comment:
            header.insert(0, f"({comment})")
        return header

    def format_tool_comment(self, tool_number: int, tool_name: str = "") -> List[str]:
        lines = [f"(Tool T{tool_number}: {tool_name or 'Default Tool'})"]
        return lines

    def format_spindle_start(
        self,
        rpm: int,
        clockwise: bool = True,
        dwell_seconds: float = 0.0,
        spindle_type: str = "router",
        router_model: Optional[str] = "dewalt_611",
        router_dial: Optional[int] = None,
    ) -> List[str]:
        lines = []
        if spindle_type == "router":
            model_name = "DeWalt DWP611" if router_model == "dewalt_611" else "Trim Router"
            dial_str = f"Set Speed Dial to #{router_dial} [~{int(rpm)} RPM]" if router_dial else f"Set Speed to ~{int(rpm)} RPM"
            lines.append(f"(Spindle: {model_name} - {dial_str})")
        else:
            lines.append(f"(Spindle: VFD / PWM Control at {int(rpm)} RPM)")

        cmd = f"M3 S{int(rpm)}" if clockwise else f"M4 S{int(rpm)}"
        lines.append(cmd)
        if dwell_seconds > 0:
            lines.append(self.format_dwell(dwell_seconds))
        return lines

    def format_spindle_stop(self) -> List[str]:
        return ["M5"]

    def format_rapid(
        self,
        x: Optional[float] = None,
        y: Optional[float] = None,
        z: Optional[float] = None,
        comment: Optional[str] = None,
    ) -> str:
        parts = ["G0"]
        if x is not None:
            parts.append(self.format_coord("X", x))
        if y is not None:
            parts.append(self.format_coord("Y", y))
        if z is not None:
            parts.append(self.format_coord("Z", z))
        if comment:
            parts.append(f"({comment})")
        return " ".join(parts)

    def format_linear(
        self,
        x: Optional[float] = None,
        y: Optional[float] = None,
        z: Optional[float] = None,
        feed_rate: Optional[float] = None,
        comment: Optional[str] = None,
    ) -> str:
        parts = ["G1"]
        if x is not None:
            parts.append(self.format_coord("X", x))
        if y is not None:
            parts.append(self.format_coord("Y", y))
        if z is not None:
            parts.append(self.format_coord("Z", z))
        if feed_rate is not None:
            parts.append(f"F{feed_rate:.1f}")
        if comment:
            parts.append(f"({comment})")
        return " ".join(parts)

    def format_dwell(self, seconds: float) -> str:
        return f"G4 P{seconds:.2f}"

    def format_footer(
        self,
        park_z: Optional[float] = None,
        park_x: Optional[float] = None,
        park_y: Optional[float] = None,
    ) -> List[str]:
        lines = ["M5 (Spindle Stop)"]
        if park_z is not None:
            lines.append(f"G0 {self.format_coord('Z', park_z)} (Retract to Clearance)")
        if park_x is not None or park_y is not None:
            park_parts = ["G0"]
            if park_x is not None:
                park_parts.append(self.format_coord("X", park_x))
            if park_y is not None:
                park_parts.append(self.format_coord("Y", park_y))
            park_parts.append("(Park)")
            lines.append(" ".join(park_parts))
        lines.append("M2 (Program End)")
        return lines

    def format_straight_drill(
        self,
        x: float,
        y: float,
        start_z: float,
        target_depth_z: float,
        retract_z: float,
        plunge_feed: float,
        dwell_seconds: float = 0.0,
        approach_clearance: float = 1.0,
    ) -> List[str]:
        """
        Grbl-expanded straight plunge cycle without G81.
        1. Rapid to safe retract plane Z
        2. Rapid to hole XY
        3. Rapid down to approach plane (start_z + clearance)
        4. Linear feed plunge to target depth Z
        5. Optional bottom dwell G4 P
        6. Rapid retract back to safe Z
        """
        lines = [
            f"(Hole at X{x:.3f} Y{y:.3f} to Z{target_depth_z:.3f})",
            self.format_rapid(z=retract_z),
            self.format_rapid(x=x, y=y),
            self.format_rapid(z=start_z + approach_clearance),
            self.format_linear(z=target_depth_z, feed_rate=plunge_feed),
        ]
        if dwell_seconds > 0:
            lines.append(self.format_dwell(dwell_seconds))
        lines.append(self.format_rapid(z=retract_z))
        return lines

    def format_arc(
        self,
        clockwise: bool,
        x: Optional[float] = None,
        y: Optional[float] = None,
        z: Optional[float] = None,
        i: Optional[float] = None,
        j: Optional[float] = None,
        r: Optional[float] = None,
        feed_rate: Optional[float] = None,
        comment: Optional[str] = None,
    ) -> str:
        """
        Formats G2 (CW) or G3 (CCW) circular or helical arc motion for Grbl.
        """
        code = "G2" if clockwise else "G3"
        parts = [code]
        if x is not None:
            parts.append(self.format_coord("X", x))
        if y is not None:
            parts.append(self.format_coord("Y", y))
        if z is not None:
            parts.append(self.format_coord("Z", z))
        if i is not None:
            parts.append(self.format_coord("I", i))
        if j is not None:
            parts.append(self.format_coord("J", j))
        if r is not None:
            parts.append(self.format_coord("R", r))
        if feed_rate is not None:
            parts.append(f"F{feed_rate:.1f}")
        if comment:
            parts.append(f"({comment})")
        return " ".join(parts)

    def format_peck_drill(
        self,
        x: float,
        y: float,
        start_z: float,
        target_depth_z: float,
        peck_depth: float,
        retract_z: float,
        plunge_feed: float,
        dwell_seconds: float = 0.0,
        approach_clearance: float = 1.0,
        peck_retract_type: str = "full_retract",
    ) -> List[str]:
        """
        Grbl-expanded peck drilling cycle without G83 canned cycles.
        Expands full chip clearing retracts or chip-break retracts linearly.
        """
        if peck_depth <= 0:
            return self.format_straight_drill(
                x=x,
                y=y,
                start_z=start_z,
                target_depth_z=target_depth_z,
                retract_z=retract_z,
                plunge_feed=plunge_feed,
                dwell_seconds=dwell_seconds,
                approach_clearance=approach_clearance,
            )

        total_depth = abs(start_z - target_depth_z)
        if total_depth <= 0.001:
            return []

        # Determine number of pecks
        num_pecks = max(1, int(math.ceil(total_depth / peck_depth)))
        actual_peck = total_depth / num_pecks

        lines = [
            f"(Peck Drilling at X{x:.3f} Y{y:.3f} to Z{target_depth_z:.3f} with Q{peck_depth:.3f})",
            self.format_rapid(z=retract_z),
            self.format_rapid(x=x, y=y),
        ]

        current_depth_z = start_z
        for p in range(1, num_pecks + 1):
            next_depth_z = start_z - (p * actual_peck)
            if p == num_pecks:
                next_depth_z = target_depth_z

            is_last = (p == num_pecks)

            if p == 1:
                lines.append(self.format_rapid(z=start_z + approach_clearance))
            else:
                # Rapid back down to just above previous peck bottom
                lines.append(self.format_rapid(z=current_depth_z + approach_clearance))

            # Controlled plunge to next depth
            lines.append(self.format_linear(z=next_depth_z, feed_rate=plunge_feed, comment=f"Peck {p}/{num_pecks}"))

            if is_last and dwell_seconds > 0:
                lines.append(self.format_dwell(dwell_seconds))

            # Retract
            if peck_retract_type == "chip_break" and not is_last:
                # Small chip breaking lift
                chip_break_z = min(retract_z, next_depth_z + approach_clearance)
                lines.append(self.format_rapid(z=chip_break_z))
            else:
                # Full retract to clear chips
                lines.append(self.format_rapid(z=retract_z))

            current_depth_z = next_depth_z

        return lines

