from typing import Dict, Type
from .base import BasePostProcessor
from .grbl import GrblPostProcessor

class StandardPostProcessor(BasePostProcessor):
    """
    Standard RS274/NGC Post-Processor supporting native canned cycles (G81, G83).
    Useful for LinuxCNC, PathPilot, and advanced controllers.
    """

    dialect_name: str = "standard"
    supports_canned_cycles: bool = True

    def format_header(
        self,
        units: str = "mm",
        absolute_mode: bool = True,
        feed_mode: str = "G94",
        plane: str = "G17",
        comment: str = None,
    ):
        unit_code = "G21" if units.lower() in ("mm", "metric") else "G20"
        dist_code = "G90" if absolute_mode else "G91"
        header = [
            "(Generated by Conversational CNC Controller - Standard G-Code)",
            f"{unit_code} {dist_code} {feed_mode} {plane} G54",
        ]
        if comment:
            header.insert(0, f"({comment})")
        return header


    def format_tool_comment(self, tool_number: int, tool_name: str = ""):
        return [f"T{tool_number} M6 ({tool_name or 'Tool'})"]

    def format_spindle_start(
        self,
        rpm: int,
        clockwise: bool = True,
        dwell_seconds: float = 0.0,
        spindle_type: str = "router",
        router_model: str = "dewalt_611",
        router_dial: int = None,
    ):
        cmd = f"M3 S{int(rpm)}" if clockwise else f"M4 S{int(rpm)}"
        lines = [cmd]
        if dwell_seconds > 0:
            lines.append(self.format_dwell(dwell_seconds))
        return lines

    def format_spindle_stop(self):
        return ["M5"]

    def format_rapid(self, x=None, y=None, z=None, comment=None):
        parts = ["G0"]
        if x is not None:
            parts.append(self.format_coord("X", x))
        if y is not None:
            parts.append(self.format_coord("Y", y))
        if z is not None:
            parts.append(self.format_coord("Z", z))
        if comment:
            parts.append(f"({comment})")
        return " ".join(parts)

    def format_linear(self, x=None, y=None, z=None, feed_rate=None, comment=None):
        parts = ["G1"]
        if x is not None:
            parts.append(self.format_coord("X", x))
        if y is not None:
            parts.append(self.format_coord("Y", y))
        if z is not None:
            parts.append(self.format_coord("Z", z))
        if feed_rate is not None:
            parts.append(f"F{feed_rate:.1f}")
        if comment:
            parts.append(f"({comment})")
        return " ".join(parts)

    def format_dwell(self, seconds: float):
        return f"G4 P{seconds:.2f}"

    def format_footer(self, park_z=None, park_x=None, park_y=None):
        lines = ["M5"]
        if park_z is not None:
            lines.append(f"G0 {self.format_coord('Z', park_z)}")
        if park_x is not None or park_y is not None:
            parts = ["G0"]
            if park_x is not None:
                parts.append(self.format_coord("X", park_x))
            if park_y is not None:
                parts.append(self.format_coord("Y", park_y))
            lines.append(" ".join(parts))
        lines.append("M30")
        return lines

    def format_straight_drill(
        self,
        x: float,
        y: float,
        start_z: float,
        target_depth_z: float,
        retract_z: float,
        plunge_feed: float,
        dwell_seconds: float = 0.0,
        approach_clearance: float = 1.0,
    ):
        # Uses standard G81 canned cycle
        dwell_part = f" P{dwell_seconds:.2f}" if dwell_seconds > 0 else ""
        cycle_code = "G82" if dwell_seconds > 0 else "G81"
        return [
            f"(Hole at X{x:.3f} Y{y:.3f})",
            f"G98 {cycle_code} X{x:.3f} Y{y:.3f} Z{target_depth_z:.3f} R{retract_z:.3f} F{plunge_feed:.1f}{dwell_part}",
            "G80 (Cancel canned cycle)",
        ]

    def format_arc(
        self,
        clockwise: bool,
        x=None,
        y=None,
        z=None,
        i=None,
        j=None,
        r=None,
        feed_rate=None,
        comment=None,
    ) -> str:
        code = "G2" if clockwise else "G3"
        parts = [code]
        if x is not None:
            parts.append(self.format_coord("X", x))
        if y is not None:
            parts.append(self.format_coord("Y", y))
        if z is not None:
            parts.append(self.format_coord("Z", z))
        if i is not None:
            parts.append(self.format_coord("I", i))
        if j is not None:
            parts.append(self.format_coord("J", j))
        if r is not None:
            parts.append(self.format_coord("R", r))
        if feed_rate is not None:
            parts.append(f"F{feed_rate:.1f}")
        if comment:
            parts.append(f"({comment})")
        return " ".join(parts)

    def format_peck_drill(
        self,
        x: float,
        y: float,
        start_z: float,
        target_depth_z: float,
        peck_depth: float,
        retract_z: float,
        plunge_feed: float,
        dwell_seconds: float = 0.0,
        approach_clearance: float = 1.0,
        peck_retract_type: str = "full_retract",
    ):
        # Uses native G83 (deep hole peck) or G73 (chip break) canned cycle
        cycle_code = "G73" if peck_retract_type == "chip_break" else "G83"
        dwell_part = f" P{dwell_seconds:.2f}" if dwell_seconds > 0 else ""
        return [
            f"(Peck Hole at X{x:.3f} Y{y:.3f})",
            f"G98 {cycle_code} X{x:.3f} Y{y:.3f} Z{target_depth_z:.3f} Q{peck_depth:.3f} R{retract_z:.3f} F{plunge_feed:.1f}{dwell_part}",
            "G80 (Cancel canned cycle)",
        ]



DIALECT_REGISTRY: Dict[str, Type[BasePostProcessor]] = {
    "grbl": GrblPostProcessor,
    "grblhal": GrblPostProcessor,
    "fluidnc": GrblPostProcessor,
    "standard": StandardPostProcessor,
    "linuxcnc": StandardPostProcessor,
}

def get_postprocessor(dialect_name: str = "grbl") -> BasePostProcessor:
    """
    Factory function returning an instance of the requested PostProcessor dialect.
    Defaults to GrblPostProcessor.
    """
    normalized_name = (dialect_name or "grbl").lower().strip()
    cls = DIALECT_REGISTRY.get(normalized_name, GrblPostProcessor)
    return cls()
