import pytest
from app.generators.sequencer import generate_job_sequence, _strip_header_and_footer


def test_strip_header_and_footer():
    gcode = """(Generated by Conversational CNC Controller)
G21 G90 G94 G17 G54
M3 S16000
G0 Z5.000
G0 X10.000 Y20.000
G1 Z-5.000 F200.0
M5
G0 Z5.000
M2
"""
    cleaned = _strip_header_and_footer(gcode)
    joined = "\n".join(cleaned)
    assert "(Generated by" not in joined
    assert "G21 G90" not in joined
    assert "M2" not in joined
    assert "G0 X10.000 Y20.000" in joined
    assert "G1 Z-5.000 F200.0" in joined


def test_generate_job_sequence_multi_op():
    operations = [
        {
            "op_name": "Face Workpiece",
            "op_type": "surfacing",
            "tool_number": 1,
            "tool_name": "Flycutter 25mm",
            "tool_diameter": 25.0,
            "spindle_speed": 14000,
            "params": {
                "length_x": 100.0,
                "width_y": 80.0,
                "total_depth": 1.0,
                "depth_per_pass": 1.0,
                "stepover": 12.0,
                "feed_rate_xy": 1200.0,
                "plunge_feed": 300.0,
            }
        },
        {
            "op_name": "Center Cavity",
            "op_type": "circular_pocket",
            "tool_number": 2,
            "tool_name": "Endmill 6.35mm",
            "tool_diameter": 6.35,
            "spindle_speed": 16000,
            "params": {
                "center_x": 50.0,
                "center_y": 40.0,
                "pocket_diameter": 30.0,
                "target_depth": 5.0,
                "depth_per_pass": 2.5,
                "stepover": 3.0,
                "feed_rate_xy": 800.0,
                "plunge_feed": 200.0,
            }
        },
        {
            "op_name": "Mounting Holes",
            "op_type": "drilling",
            "tool_number": 2,  # Same tool T2
            "tool_name": "Endmill 6.35mm",
            "tool_diameter": 6.35,
            "spindle_speed": 16000,
            "params": {
                "hole_pattern_type": "grid",
                "grid_rows": 2,
                "grid_cols": 2,
                "grid_spacing_x": 80.0,
                "grid_spacing_y": 60.0,
                "target_depth": 6.0,
                "plunge_feed": 250.0,
            }
        },
    ]

    result = generate_job_sequence(
        job_name="Bracket Milling",
        operations=operations,
        safe_z_retract=5.0,
        units="mm",
        dialect="grbl",
        optimize_tool_order=False,
    )

    gcode = result["gcode"]
    
    # Verify top header and footer
    assert "Job: Bracket Milling" in gcode
    assert "G21 G90 G94 G17 G54" in gcode
    assert "M2" in gcode
    assert "M5" in gcode

    # Verify operation banners
    assert ">>> OP 1/3: FACE WORKPIECE [SURFACING] <<<" in gcode
    assert ">>> OP 2/3: CENTER CAVITY [CIRCULAR_POCKET] <<<" in gcode
    assert ">>> OP 3/3: MOUNTING HOLES [DRILLING] <<<" in gcode

    # Verify tool change count: T1 (Op1) -> T2 (Op2) -> T2 reused (Op3, no redundant tool change!)
    assert result["tool_change_count"] == 2
    assert len(result["tools_used"]) == 2


def test_all_operation_types_in_sequence():
    operations = [
        {
            "op_name": "Face Stock",
            "op_type": "surfacing",
            "tool_number": 1,
            "tool_name": "Flycutter",
            "tool_diameter": 25.0,
            "params": {
                "length_x": 100.0,
                "width_y": 100.0,
                "total_depth_z": 1.0,
                "stepdown_z": 1.0,
                "stepover_percent": 60.0,
            }
        },
        {
            "op_name": "Deep Peck Holes",
            "op_type": "peck_drilling",
            "tool_number": 2,
            "tool_name": "1/8 Drill",
            "tool_diameter": 3.175,
            "params": {
                "holes": [[10.0, 10.0], [90.0, 10.0]],
                "target_depth_z": -12.0,
                "peck_depth": 3.0,
                "peck_retract_type": "full_retract",
            }
        },
        {
            "op_name": "Helical M8 Thread",
            "op_type": "thread_milling",
            "tool_number": 3,
            "tool_name": "Single Point Thread Mill",
            "tool_diameter": 6.0,
            "params": {
                "holes": [[50.0, 50.0]],
                "nominal_diameter": 8.0,
                "pitch": 1.25,
                "thread_length": 10.0,
                "thread_type": "internal",
            }
        },
        {
            "op_name": "Center Bore",
            "op_type": "circular_pocket",
            "tool_number": 4,
            "tool_name": "1/4 Endmill",
            "tool_diameter": 6.35,
            "params": {
                "pockets": [[50.0, 50.0]],
                "pocket_diameter": 25.0,
                "target_depth_z": -5.0,
                "stepdown_z": 2.5,
                "stepover_percent": 50.0,
            }
        },
        {
            "op_name": "Engrave Serial",
            "op_type": "engraving",
            "tool_number": 5,
            "tool_name": "60deg V-Bit",
            "tool_diameter": 3.175,
            "params": {
                "text": "SN-2026",
                "layout_mode": "linear",
                "start_x": 10.0,
                "start_y": 90.0,
                "font_size": 8.0,
                "target_depth_z": -0.3,
            }
        },
        {
            "op_name": "Linear Keyway Slot",
            "op_type": "linear_slot",
            "tool_number": 4,
            "tool_name": "1/4 Endmill",
            "tool_diameter": 6.35,
            "params": {
                "start_x": 20.0,
                "start_y": 50.0,
                "end_x": 80.0,
                "end_y": 50.0,
                "total_depth": 3.0,
                "depth_per_pass": 1.5,
            }
        },
        {
            "op_name": "Deburr Edge Chamfer",
            "op_type": "rectangular_chamfer",
            "tool_number": 5,
            "tool_name": "60deg V-Bit",
            "tool_diameter": 3.175,
            "params": {
                "length_x": 100.0,
                "width_y": 100.0,
                "chamfer_width": 1.0,
                "v_bit_angle_deg": 90.0,
            }
        }
    ]

    result = generate_job_sequence(
        job_name="Full Master Part Job",
        operations=operations,
        safe_z_retract=5.0,
        units="mm",
        dialect="grbl",
    )

    assert result["operation_count"] == 7
    gcode = result["gcode"]
    assert ">>> OP 1/7: FACE STOCK" in gcode
    assert ">>> OP 2/7: DEEP PECK HOLES" in gcode
    assert ">>> OP 3/7: HELICAL M8 THREAD" in gcode
    assert ">>> OP 4/7: CENTER BORE" in gcode
    assert ">>> OP 5/7: ENGRAVE SERIAL" in gcode
    assert ">>> OP 6/7: LINEAR KEYWAY SLOT" in gcode
    assert ">>> OP 7/7: DEBURR EDGE CHAMFER" in gcode

