"""
Multi-Operation Job Program Sequencer / Builder Engine.
Bundles multiple conversational machining operations into a single cohesive, production-ready .nc job file.
Features:
- Single top-level safety header (G21 G90 G94 G17 G54) and program footer (M5, G0 Z, G0 XY, M2/M30)
- Intelligent Tool Change Optimization: Eliminates redundant M6/M0 pauses when adjacent operations share the same tool
- Safe inter-operation retract planes (G0 Z<safe_z>) and coordinate continuity
- Operation section banners, tool comments, and aggregate job telemetry (lines, tool count, bounding box)
"""
import inspect
from typing import Dict, Any, List, Optional
from ..postprocessors import get_postprocessor
from .drilling import generate_straight_plunge, generate_peck_drilling
from .thread_milling import generate_helical_thread_milling

from .circular_pocket import generate_circular_pocket
from .rectangular_pocket import generate_rectangular_pocket, generate_rectangular_boss
from .slotting import generate_linear_slot
from .chamfering import generate_rectangular_chamfer
from .surfacing import generate_surfacing
from .engraving import generate_text_engraving
from .contouring import generate_contour_profile
from .base import strip_header_and_footer
from .mesh_leveling import WorkpieceMeshMap

_strip_header_and_footer = strip_header_and_footer

GENERATOR_MAP = {
    "drilling": generate_straight_plunge,
    "straight_plunge": generate_straight_plunge,
    "peck_drilling": generate_peck_drilling,
    "thread_milling": generate_helical_thread_milling,
    "circular_pocket": generate_circular_pocket,
    "rectangular_pocket": generate_rectangular_pocket,
    "rectangular_boss": generate_rectangular_boss,
    "linear_slot": generate_linear_slot,
    "slotting": generate_linear_slot,
    "rectangular_chamfer": generate_rectangular_chamfer,
    "chamfering": generate_rectangular_chamfer,
    "surfacing": generate_surfacing,
    "engraving": generate_text_engraving,
    "contouring": generate_contour_profile,
    "profile": generate_contour_profile,
}





def _strip_header_and_footer(gcode_text: str) -> List[str]:
    """
    Strips dialect header (G21 G90 G94...) and footer (M5, G0 park, M2/M30)
    from a standalone operation snippet so it can be cleanly stitched.
    """
    lines = [line.strip() for line in gcode_text.splitlines() if line.strip()]
    cleaned = []
    for line in lines:
        upper = line.upper()
        # Skip header metadata / dialect setup
        if upper.startswith("(GENERATED BY") or upper.startswith("(TARGET:"):
            continue
        if "G21 G90" in upper or "G20 G90" in upper or "G21 G91" in upper or "G20 G91" in upper:
            continue
        # Skip program termination footer lines
        if upper in ("M2", "M30", "M02"):
            continue
        cleaned.append(line)

    # Trim trailing M5 from individual operations if present
    while cleaned and cleaned[-1].upper() == "M5":
        cleaned.pop()

    return cleaned


def generate_job_sequence(
    job_name: str = "Multi-Op Job",
    operations: Optional[List[Dict[str, Any]]] = None,
    safe_z_retract: float = 5.0,
    units: str = "mm",
    dialect: str = "grbl",
    optimize_tool_order: bool = False,
    park_x: Optional[float] = 0.0,
    park_y: Optional[float] = 0.0,
    park_z: Optional[float] = 5.0,
    apply_mesh_leveling: bool = False,
    mesh_data: Optional[Dict[str, Any]] = None,
    mesh_max_segment_length: float = 3.0,
) -> Dict[str, Any]:
    """
    Stitches multiple conversational operations into a single unified .nc program.
    Supports dynamic workpiece surface mesh leveling across all follow-on operations.
    """
    if not operations:
        operations = []

    post = get_postprocessor(dialect)
    ops_to_process = list(operations)

    mesh_map_obj: Optional[WorkpieceMeshMap] = None
    if apply_mesh_leveling and mesh_data and mesh_data.get("points"):
        try:
            mesh_map_obj = WorkpieceMeshMap(
                points=mesh_data["points"],
                shape_type=mesh_data.get("shape_type", "rectangle"),
                shape_meta=mesh_data.get("shape_meta", {}),
            )
        except Exception:
            mesh_map_obj = None

    if optimize_tool_order and len(ops_to_process) > 1:
        # Group operations by tool_number while maintaining sub-order
        ops_to_process.sort(key=lambda op: int(op.get("tool_number", 1)))

    full_lines = []
    
    # 1. Top-Level Job Header
    job_comment = f"Job: {job_name} | {len(ops_to_process)} Operations"
    if mesh_map_obj:
        job_comment += f" | Mesh Leveling: ACTIVE ({mesh_map_obj.shape_type.upper()}, {len(mesh_map_obj.active_points)} pts)"

    header = post.format_header(
        units=units,
        absolute_mode=True,
        comment=job_comment,
    )
    full_lines.extend(header)
    if mesh_map_obj:
        full_lines.append(f"( Workpiece Surface Mesh Compensation: {mesh_map_obj.shape_type.upper()} )")
        full_lines.append(f"( Surface Elevation Span: {mesh_map_obj.z_min:+.3f}mm to {mesh_map_obj.z_max:+.3f}mm | Delta: {mesh_map_obj.z_span:.3f}mm )")
    full_lines.append("")

    active_tool_number: Optional[int] = None
    active_spindle_rpm: Optional[int] = None
    tool_list: List[Dict[str, Any]] = []
    tool_change_count = 0

    all_holes = []
    all_pockets = []
    combined_bounding_box = {"min_x": 0.0, "max_x": 0.0, "min_y": 0.0, "max_y": 0.0, "min_z": 0.0, "max_z": 0.0}

    for idx, op in enumerate(ops_to_process, 1):
        op_name = op.get("op_name", f"Op {idx}")
        op_type = (op.get("op_type") or "drilling").lower().strip()
        t_num = int(op.get("tool_number", 1))
        t_name = op.get("tool_name", f"Tool T{t_num}")
        t_dia = float(op.get("tool_diameter", 3.175))
        rpm = int(op.get("spindle_speed", 16000))
        params = op.get("params", {}) or {}

        # Track tools used
        if not any(t["tool_number"] == t_num for t in tool_list):
            tool_list.append({"tool_number": t_num, "name": t_name, "diameter": t_dia})

        # Section Banner
        full_lines.append("( --------------------------------------------------- )")
        full_lines.append(f"( >>> OP {idx}/{len(ops_to_process)}: {op_name.upper()} [{op_type.upper()}] <<< )")
        full_lines.append(f"( Tool: T{t_num} ({t_name}) | Diameter: {t_dia:.3f}{units} )")
        full_lines.append("( --------------------------------------------------- )")

        # Tool Change (only if tool number changed or first tool)
        if active_tool_number != t_num:
            tool_change_count += 1
            if active_tool_number is not None:
                # Retract and stop spindle before tool change
                full_lines.append("M5 (Spindle Stop for Tool Change)")
                full_lines.append(f"G0 Z{safe_z_retract:.3f} (Safe Retract)")
            
            tool_comments = post.format_tool_comment(t_num, t_name)
            full_lines.extend(tool_comments)
            active_tool_number = t_num

        # Spindle Speed Check
        if active_spindle_rpm != rpm:
            spindle_lines = post.format_spindle_start(rpm=rpm, clockwise=True, dwell_seconds=1.5)
            full_lines.extend(spindle_lines)
            active_spindle_rpm = rpm

        # Generate or extract Operation Body
        if "raw_gcode" in op and op["raw_gcode"]:
            op_lines = _strip_header_and_footer(op["raw_gcode"])
        else:
            gen_func = GENERATOR_MAP.get(op_type)
            if not gen_func and op_type in ("soft_jaw", "soft_jaw_fixture"):
                from .nesting import generate_soft_jaw_fixture
                gen_func = generate_soft_jaw_fixture
            if gen_func:
                # Merge top-level params with op params
                call_params = dict(params)
                call_params.setdefault("tool_number", t_num)
                call_params.setdefault("tool_name", t_name)
                call_params.setdefault("tool_diameter", t_dia)
                call_params.setdefault("spindle_speed", rpm)
                call_params.setdefault("units", units)
                call_params.setdefault("dialect", dialect)
                call_params.setdefault("safe_z_retract", safe_z_retract)

                sig = inspect.signature(gen_func)
                accepted_keys = set(sig.parameters.keys())
                has_var_kw = any(p.kind == inspect.Parameter.VAR_KEYWORD for p in sig.parameters.values())

                if not has_var_kw:
                    filtered_params = {k: v for k, v in call_params.items() if k in accepted_keys}
                else:
                    filtered_params = call_params

                if "retract_z" in accepted_keys and "retract_z" not in filtered_params and "safe_z_retract" in call_params:
                    filtered_params["retract_z"] = call_params["safe_z_retract"]

                try:
                    op_result = gen_func(**filtered_params)
                    if hasattr(op_result, "gcode"):
                        raw_gc = op_result.gcode
                    elif isinstance(op_result, dict):
                        raw_gc = op_result.get("gcode", "")
                    else:
                        raw_gc = str(op_result)

                    op_lines = _strip_header_and_footer(raw_gc)
                    if isinstance(op_result, dict):
                        if "holes" in op_result:
                            all_holes.extend(op_result["holes"])
                        if "pockets" in op_result:
                            all_pockets.extend(op_result["pockets"])
                except Exception as e:
                    op_lines = [f"(Error generating {op_name}: {str(e)})"]
            else:
                op_lines = [f"(Unknown operation type: {op_type})"]

        # Apply workpiece surface mesh warping if active
        if mesh_map_obj and op_lines:
            op_raw_str = "\n".join(op_lines)
            warped_str = mesh_map_obj.warp_gcode(op_raw_str, max_segment_length=mesh_max_segment_length)
            op_lines = warped_str.splitlines()

        full_lines.extend(op_lines)
        # Safe intermediate retract at end of operation
        full_lines.append(f"G0 Z{safe_z_retract:.3f} (End of Op {idx} Retract)")
        full_lines.append("")

    # 3. Final Unified Program Footer
    footer = post.format_footer(park_z=park_z, park_x=park_x, park_y=park_y)
    full_lines.extend(footer)

    full_gcode = "\n".join(full_lines)

    return {
        "job_name": job_name,
        "operation_count": len(ops_to_process),
        "tool_change_count": tool_change_count,
        "tools_used": tool_list,
        "gcode": full_gcode,
        "line_count": len(full_lines),
        "holes": all_holes,
        "pockets": all_pockets,
        "mesh_leveling_applied": mesh_map_obj is not None,
        "mesh_summary": mesh_map_obj.to_dict() if mesh_map_obj else None,
    }
